name: Commit CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '![0-9]+.*'
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Prepare Python embed
        run: |
          curl -O https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-win32.zip
          curl -O https://bootstrap.pypa.io/get-pip.py
          7z x python-3.8.10-embed-win32.zip -opython-3.8.10-embed-win32\
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            .\*
        if: ${{ success() }}

